apiVersion: apps/v1
kind: Deployment
metadata:
  name: static-site
spec:
  replicas: 3
  selector:
    matchLabels:
      app: static-site
  template:
    metadata:
      labels:
        app: static-site
    spec:
      containers:
        - name: static-site
          image: httpd:alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/local/apache2/htdocs
              name: static-site-volume
  volumes:
    - name: static-site-volume
      hostPath:
        path: /vagrant/static-site
---
apiVersion: v1
kind: Service
metadata:
  name: static-site-service
spec:
  selector:
    app: static-site
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
